module Cavendish
  module Commands
    class AddTailwind < Cavendish::Commands::Base
      def perform
        install_tailwind_rn_dependencies
        run_setup_script
        ignore_tailwind_rn_autogenerated_files
      end

      private

      def install_tailwind_rn_dependencies
        run_in_project('yarn add tailwind-rn')
      end

      def run_setup_script
        run_in_project('npx setup-tailwind-rn')
      end

      def ignore_tailwind_rn_autogenerated_files
        inject_to_file('.gitignore', gitignore_content)
      end

      def gitignore_content
        <<~GITIGNORE

          # tailwind-rn
          tailwind.css
          tailwind.json
        GITIGNORE
      end
    end
  end
end
